### ISSUE TITLE
构建镜像: bin/build.[sh|ps1]（镜像中不含游戏本体，只有用于下载游戏的 SteamCMD ） 运行镜像: bin/run_docker.[sh|ps1]

### ISSUE THREAD

**Issue by Hudson-SanMu** [lyy289065406/ark-server-docker#2]
### 找不到命令
steam@Ubuntu-Test:~/ark-server-docker$ bin/build.[sh|ps1]
bash: bin/build.[sh: 没有那个文件或目录
ps1]：未找到命令
steam@Ubuntu-Test:~/ark-server-docker$ bin/run_docker.[sh|ps1]
bash: bin/run_docker.[sh: 没有那个文件或目录
ps1]：未找到命令
steam@Ubuntu-Test:~/ark-server-docker$ bin/install_game.[sh|ps1]
bash: bin/install_game.[sh: 没有那个文件或目录
ps1]：未找到命令

**Comment by 2694484453** [comment]
是.sh文件不带|ps1

**Comment by lyy289065406** [comment]
> ### 找不到命令
> steam@Ubuntu-Test:~/ark-server-docker$ bin/build.[sh|ps1] bash: bin/build.[sh: 没有那个文件或目录 ps1]：未找到命令 steam@Ubuntu-Test:~/ark-server-docker$ bin/run_docker.[sh|ps1] bash: bin/run_docker.[sh: 没有那个文件或目录 ps1]：未找到命令 steam@Ubuntu-Test:~/ark-server-docker$ bin/install_game.[sh|ps1] bash: bin/install_game.[sh: 没有那个文件或目录 ps1]：未找到命令

你问的问题说明都有写，不看就来问的？ 命令都搞不懂不建议用
